import ReduxProvider from "@/Redux/Reduxorivider/ReduxProvider";
import "./globals.css";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import NavbarComp from "@/Components/Navbar/NavbarComp";
import FooterComp from "@/Components/Footer/FooterComp";

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MHState-Find Your Property || Home Page ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  max-w-screen-2xl mx-auto px-2.5 md:px-10 container bg-slate-200/30 drop-shadow-lg text-black`}
      >
        <ReduxProvider>
          <NavbarComp />
          {children}
          <FooterComp />
        </ReduxProvider>
      </body>
    </html>
  );
}
